version: '3.4'
services:
    db:
        image: viniciusmontouro/mysql-farmacia-apontador
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: farmacia-apontador
        ports:
          - "3308:3306"
        networks:
          - apontador-networks
    farmacia-apontador:
        image: viniciusmontouro/farmacia-apontador
        restart: always
        build: ./ProjetoFarmacia
        working_dir: /ProjetoFarmacia
        environment:
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes:
          - ./ProjetoFarmacia:/ProjetoFarmacia
          - ~/.m2:/root/.m2
        ports:
          - "8080:8080"
        command: mvn clean spring-boot:run
        links:
          - db
        depends_on:
          - db
        networks:
          - apontador-networks
    web:
        build:
          context: ./frontend-farmacia
          dockerfile: Dockerfile
        ports:
          - "4200:4200"
        volumes:
          - /app/node_modules
          - .:/app
        networks:
          - apontador-networks
networks:
    apontador-networks:
        driver: bridge